[package]
edition = "2021"
name = "bevy_heightmap"
version = "0.4.0"
authors = ["Josiah Putman <joshikatsu@gmail.com>"]
description = "Create meshes from heightmap PNGs in the Bevy game engine."
documentation = "https://docs.rs/bevy_heightmap/latest/bevy_heightmap"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/Katsutoshii/bevy_heightmap"
repository = "https://github.com/Katsutoshii/bevy_heightmap"
keywords = [
    "bevy"
]
readme = "README.md"
exclude = ["assets/*"]

[dependencies]
bevy = "0.16"
image = "0.25"
thiserror = "2.0"

[dev-dependencies]
bevy-inspector-egui = "0.31"
bevy_egui = { version = "0.34.0", default-features = false }

[[example]]
name = "image"

[[example]]
name = "value_function"

[[example]]
name = "export_heightmap"
